# Generated by Django 6.0.5 on 2026-05-06 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('category', models.CharField(choices=[('books', 'Libros'), ('games', 'Juegos'), ('music', 'Música'), ('figures', 'Figuras'), ('other', 'Otros')], default='other', max_length=20, verbose_name='categoría')),
                ('visibility', models.CharField(choices=[('private', 'Privada'), ('public', 'Pública')], default='private', max_length=10, verbose_name='visibilidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='propietario')),
            ],
            options={
                'verbose_name': 'colección',
                'verbose_name_plural': 'colecciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('personal_comment', models.TextField(blank=True, verbose_name='comentario personal')),
                ('status', models.CharField(choices=[('owned', 'En posesión'), ('wanted', 'Deseado'), ('sold', 'Vendido'), ('lent', 'Prestado')], default='owned', max_length=10, verbose_name='estado')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='carátula')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='posición')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='collections.collection', verbose_name='colección')),
            ],
            options={
                'verbose_name': 'elemento',
                'verbose_name_plural': 'elementos',
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['owner', '-created_at'], name='collections_owner_i_f52590_idx'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_collection_owner_slug'),
        ),
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['collection', 'position'], name='collections_collect_ba6ccb_idx'),
        ),
    ]
