# Generated by Django 6.0.5 on 2026-05-06 13:53

import django.db.models.deletion
from django.db import migrations, models

import apps.collections.validators


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=apps.collections.validators.rename_cover, validators=[apps.collections.validators.validate_cover], verbose_name='carátula'),
        ),
        migrations.CreateModel(
            name='CollectionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='posición')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='collections.collection', verbose_name='colección')),
            ],
            options={
                'verbose_name': 'grupo',
                'verbose_name_plural': 'grupos',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='collections.collectiongroup', verbose_name='grupo'),
        ),
        migrations.AddConstraint(
            model_name='collectiongroup',
            constraint=models.UniqueConstraint(fields=('collection', 'slug'), name='unique_group_collection_slug'),
        ),
    ]
