# Generated by Django 6.0.5 on 2026-05-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0002_alter_collectionitem_cover_collectiongroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='cantidad'),
        ),
    ]
