# Generated by Django 6.0.5 on 2026-05-06 14:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], max_length=20, verbose_name='nivel')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('max_collections', models.PositiveIntegerField(blank=True, null=True, verbose_name='máx. colecciones')),
                ('max_items_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='máx. elementos totales')),
                ('max_storage_bytes', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='almacenamiento máx. (bytes)')),
                ('can_upload_custom_images', models.BooleanField(default=True, verbose_name='puede subir imágenes propias')),
                ('can_use_public_collections', models.BooleanField(default=False, verbose_name='puede usar colecciones públicas')),
                ('can_use_groups', models.BooleanField(default=False, help_text='False en free. True en premium. Si el usuario baja a free, sus grupos existentes se conservan pero no puede crear nuevos.', verbose_name='puede crear grupos')),
                ('can_use_advanced_features', models.BooleanField(default=False, verbose_name='puede usar funciones avanzadas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'planes',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('suspended', 'Suspendida'), ('canceled', 'Cancelada'), ('expired', 'Vencida')], default='active', max_length=20, verbose_name='estado')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='inicio')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='inicio periodo actual')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='fin periodo actual')),
                ('grace_until', models.DateTimeField(blank=True, null=True, verbose_name='gracia hasta')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelada en')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='suspendida en')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizada en')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='renovación automática')),
                ('provider', models.CharField(blank=True, max_length=50, verbose_name='proveedor')),
                ('provider_customer_id', models.CharField(blank=True, max_length=200, verbose_name='ID cliente externo')),
                ('provider_subscription_id', models.CharField(blank=True, max_length=200, verbose_name='ID suscripción externa')),
                ('external_reference', models.CharField(blank=True, max_length=200, verbose_name='referencia externa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan', verbose_name='plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'suscripción',
                'verbose_name_plural': 'suscripciones',
                'ordering': ['-started_at'],
            },
        ),
    ]
