# Copyright (c) 2026 Raúl Esteban Posadilla. Todos los derechos reservados.
# Software privativo. Uso no autorizado expresamente prohibido.
# Generated by Django 6.0.5 on 2026-05-06 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_usado', models.CharField(blank=True, max_length=254, verbose_name='email usado')),
                ('evento', models.CharField(choices=[('login_ok', 'Login correcto'), ('login_fail', 'Login fallido'), ('logout', 'Logout'), ('password_change', 'Cambio de contraseña'), ('password_reset', 'Recuperación de contraseña')], max_length=20, verbose_name='evento')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='fecha y hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
